language: node_js
node_js:
  - "node"

cache: npm

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
#  - npm install -g ionic #Verificar se precisa no deploy do Travis

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN




